[package]
name = "slmd"
version = "0.1.0"
edition = "2021"

[dependencies]
daemonize="0.5.0"
csv="1.3.1"
sysinfo = "0.33.0"
confy = "0.6.1"
serde = { version = "1.0.215", features = ["derive"] }
chrono = "0.4.38"